owner: belhyun
repo: yonsei-upptime
user-agent: KojBot

# Add your sites here
sites:
  - name: Portal - https://portal.yonsei.ac.kr/main/
    url: https://portal.yonsei.ac.kr/main/
  - name: Infra - https://infra.yonsei.ac.kr
    url: https://infra.yonsei.ac.kr
  - name: GroupWare - https://ysgw.yonsei.ac.kr
    url: https://ysgw.yonsei.ac.kr

# Add downtime notifications
# https://upptime.js.org/docs/notifications
notifications:
  - type: slack
    channel: CDMRWJU4T
#assignees:
#  - AnandChowdhary

# Configure your status website
# http://localhost:3000/docs/configuration#status-website
status-website:
  # cname: upptime.js.org
  baseUrl: /yonsei-upptime # Base directory for GitHub Pages (remove if have a custom domain)
  logoUrl: https://gitlab.yonsei.ac.kr/uploads/-/system/appearance/logo/1/%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C__1_.png
  name: 연세대학교 IT서비스팀 서비스 헬스체크(5분주기)
  introTitle:
  introMessage: 서비스 현황
