owner: belhyun
repo: yonsei-upptime
user-agent: KojBot

# Add your sites here
sites:
  - name: Portal-1(48) - https://nportal0.yonsei.ac.kr:8443/main
    url: https://nportal0.yonsei.ac.kr:8443/main
  - name: Portal-2(49) - https://nportal1.yonsei.ac.kr:8443/main
    url: https://nportal1.yonsei.ac.kr:8443/main
  - name: Infra-1(12) - http://ninfra0.yonsei.ac.kr:8082
    url: http://ninfra0.yonsei.ac.kr:8082
  - name: Infra-2(13) - http://ninfra1.yonsei.ac.kr:8082/sso/L4_response.html
    url: http://ninfra1.yonsei.ac.kr:8082/sso/L4_response.html
  - name: GroupWare - https://ysgw.yonsei.ac.kr
    url: https://ysgw.yonsei.ac.kr
  - name: Donasys - https://donasys.yonsei.ac.kr/donasys
    url: https://donasys.yonsei.ac.kr/donasys
  - name: Tams - https://tams.yonsei.ac.kr:8443/
    url: https://tams.yonsei.ac.kr:8443/
  - name: Sms - https://message.yonsei.ac.kr/include/noPermission.jsp
    url: https://message.yonsei.ac.kr/include/noPermission.jsp
  - name: Sugang(undergraduate)
    url: https://ysweb.yonsei.ac.kr/websquare/websquare.jsp?w2xPath=/wq/login/hakbu_login.xml
  - name: Sugang(graduate)
    url: https://ysweb.yonsei.ac.kr/graduate.jsp
  - name: Grade - https://ysweb.yonsei.ac.kr/grade.jsp
    url: https://ysweb.yonsei.ac.kr/grade.jsp


# Add downtime notifications
# https://upptime.js.org/docs/notifications
notifications:
  - type: slack
    channel: CDMRWJU4T
#assignees:
#  - AnandChowdhary

# Configure your status website
# http://localhost:3000/docs/configuration#status-website
status-website:
  # cname: upptime.js.org
  baseUrl: /yonsei-upptime # Base directory for GitHub Pages (remove if have a custom domain)
  logoUrl: https://gitlab.yonsei.ac.kr/uploads/-/system/appearance/logo/1/%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C__1_.png
  name: 연세대학교 IT서비스팀 서비스 헬스체크(5분주기)
  introTitle:
  introMessage: 서비스 현황
