owner: belhyun
repo: upptime
user-agent: KojBot

# Add your sites here
sites:
  - name: 연세포털 - https://portal.yonsei.ac.kr/main/
    url: https://portal.yonsei.ac.kr/main/

# Add downtime notifications
# https://upptime.js.org/docs/notifications
notifications:
  - type: slack
    channel: C016QTU9S9Y
assignees:
  - AnandChowdhary

# Configure your status website
# http://localhost:3000/docs/configuration#status-website
status-website:
  # cname: upptime.js.org
  cname: belhyun.github.io
  baseUrl: /status/ # Base directory for GitHub Pages (remove if have a custom domain)
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: 연세대학교 IT서비스팀에서 운영되는 서비스들의 현재 상태입니다. GitHub Actions 를 이용한 Upptime 으로 운영되고 있습니다.
