owner: belhyun
repo: yonsei-upptime
user-agent: KojBot

# Add your sites here
sites:
  - name: 연세포털 - https://portal.yonsei.ac.kr/main/
    url: https://portal.yonsei.ac.kr/main/
  - name: 인프라 - https://infra.yonsei.ac.kr
    url: https://infra.yonsei.ac.kr
  - name: 그룹웨어 - https://ysgw.yonsei.ac.kr
    url: https://ysgw.yonsei.ac.kr

# Add downtime notifications
# https://upptime.js.org/docs/notifications
notifications:
  - type: slack
    channel: CDMRWJU4T
#assignees:
#  - AnandChowdhary

# Configure your status website
# http://localhost:3000/docs/configuration#status-website
status-website:
  # cname: upptime.js.org
  baseUrl: /yonsei-upptime # Base directory for GitHub Pages (remove if have a custom domain)
  logoUrl: https://gitlab.yonsei.ac.kr/uploads/-/system/appearance/logo/1/%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C__1_.png
  name: 연세대학교 서비스 헬스체크
  introTitle: 연세대학교 IT서비스팀에서 운영되는 서비스들의 현재 상태입니다. GitHub Actions 를 이용한 Upptime 으로 운영되고 있습니다.
  introMessage: 서비스 현황
